### ISSUE TITLE
Test Case: Login Functionality - Valid Credentials.

### ISSUE THREAD

**Issue by Amrsr4** [EslamAshraf6595/swProject#19]
## Test Case: Login Functionality - Valid Credentials

**Function**: Login  
**Scenario**: Valid Login Credentials  
**Steps**:
1. Open the login page.
2. Enter valid email and password.
3. Click "Login."

**Expected Result**:
The user is redirected to the homepage.

**Status**:
Pending

**Comment by AShalaby2004** [comment]
Done
